# Generated by Django 5.0.7 on 2025-03-07 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_usuario_perfil_user_perfil_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
