# Generated by Django 5.0.7 on 2025-03-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_rename_user_perfil_user_alter_perfil_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='User',
            new_name='usuario',
        ),
    ]
