# Generated by Django 5.1.7 on 2025-03-11 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_categoria_estado_categoria_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=50),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
