# Generated by Django 5.1.7 on 2025-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_carrito_estado_carrito_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
